name: Publish Docker
on: [push]
jobs:
  main:
    if: github.ref == 'refs/heads/master'
    name: Publish Docker
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
        with:
          ref: ${{ github.ref }}
      - name: Login to Github Docker Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u edenlabllc --password-stdin
      - name: Build, tag, and push image to Amazon ECR
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker build -t docker.pkg.github.com/edenlabllc/traefik-tower/traefik-tower:$IMAGE_TAG .
          docker push docker.pkg.github.com/edenlabllc/traefik-tower/traefik-tower:$IMAGE_TAG
      - name: Logout of Amazon ECR
        if: always()
        run: docker logout edenlabllc